[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "*"
egg = "0.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"


[features]
skip_isabelle = []
