// AUTO-GENERATED BY build.rs

use hello_world::*;

#[allow(unused_imports)] use std::path::PathBuf;


#[test]
fn bitvector_arith_commutativity_add() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("commutativity_add");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "commutativity_add",
        &[],
        "(bw r ( + (bw p a) (bw q b)))",
        "(bw r ( + (bw q b) (bw p a)))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_commutativity_mult() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("commutativity_mult");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "commutativity_mult",
        &[],
        "(bw r ( * (bw p a) (bw q b)))",
        "(bw r ( * (bw q b) (bw p a)))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_mult_assoc_1() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("mult_assoc_1");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "mult_assoc_1",
        &["(>= q t)", "(>= u t)"],
        "(bw t ( * (bw u (* (bw p a) (bw r b))) (bw s c)))",
        "(bw t ( * (bw p a) (bw q (* (bw r b) (bw s c)))))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_mult_assoc_2() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("mult_assoc_2");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "mult_assoc_2",
        &["(>= q t)", "(<= (+ p r) u)"],
        "(bw t ( * (bw u (* (bw p a) (bw r b))) (bw s c)))",
        "(bw t ( * (bw p a) (bw q (* (bw r b) (bw s c)))))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_mult_assoc_3() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("mult_assoc_3");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "mult_assoc_3",
        &["(<= (+ r s) q)", "(>= u t)"],
        "(bw t ( * (bw u (* (bw p a) (bw r b))) (bw s c)))",
        "(bw t ( * (bw p a) (bw q (* (bw r b) (bw s c)))))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_mult_assoc_4() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("mult_assoc_4");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "mult_assoc_4",
        &["(<= (+ r s) q)", "(<= (+ p r) u)"],
        "(bw t ( * (bw u (* (bw p a) (bw r b))) (bw s c)))",
        "(bw t ( * (bw p a) (bw q (* (bw r b) (bw s c)))))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_add_assoc_1() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("add_assoc_1");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "add_assoc_1",
        &["(>= q t)", "(>= u t)"],
        "(bw t ( + (bw u (+ (bw p a) (bw r b))) (bw s c)))",
        "(bw t ( + (bw p a) (bw q (+ (bw r b) (bw s c)))))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_add_assoc_2() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("add_assoc_2");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "add_assoc_2",
        &["(< r q)", "(< s q)", "(>= u t)"],
        "(bw t ( + (bw u (+ (bw p a) (bw r b))) (bw s c)))",
        "(bw t ( + (bw p a) (bw q (+ (bw r b) (bw s c)))))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_add_assoc_3() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("add_assoc_3");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "add_assoc_3",
        &["(>= q t)", "(< p u)", "(< r u)"],
        "(bw t ( + (bw u (+ (bw p a) (bw r b))) (bw s c)))",
        "(bw t ( + (bw p a) (bw q (+ (bw r b) (bw s c)))))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_add_assoc_4() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("add_assoc_4");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "add_assoc_4",
        &["(< r q)", "(< s q)", "(< p u)", "(< r u)"],
        "(bw t ( + (bw u (+ (bw p a) (bw r b))) (bw s c)))",
        "(bw t ( + (bw p a) (bw q (+ (bw r b) (bw s c)))))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_dist_over_add() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("dist_over_add");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "dist_over_add",
        &["(>= q r)", "(>= u r)", "(>= v r)"],
        "(bw r (* (bw p a) (+ (bw s b) (bw t c))))",
        "(bw r (+ (bw u (* (bw p a) (bw s b))) (bw v (* (bw p a) (bw t c)) ) ))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_sum_same() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("sum_same");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "sum_same",
        &[],
        "(bw q (+ (bw p a) (bw p a)))",
        "(bw q (* (bw 2 2) (bw p a)))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_mult_sum_same() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("mult_sum_same");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "mult_sum_same",
        &["(> t p)", "(> t 1)", "(>= s (+ p q))"],
        "(bw r (+ (bw s (* (bw p a) (bw q b))) (bw q b)))",
        "(bw r (* (bw t (+ (bw p a) (bw 1 1))) (bw q b)))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_add_zero() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("add_zero");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "add_zero",
        &["(>= p p)"],
        "(bw p (+ (bw p a) (bw q 0)))",
        "(bw p a)",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_sub_to_neg() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("sub_to_neg");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "sub_to_neg",
        &[],
        "(bw r (- (bw p a) (bw q b)))",
        "(bw r (+ (bw p a) (- (bw q b))))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_mul_one() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("mul_one");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "mul_one",
        &["(>= p p)"],
        "(bw p (* (bw p a) (bw q 1)))",
        "(bw p a)",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}


#[test]
fn bitvector_arith_mul_two() {
    let output_dir = PathBuf::from("target")
        .join("tests")
        .join("bitvector_arith")
        .join("mul_two");
    prepare_output_dir(&output_dir);
    let eq = Equivalence::new(
        "mul_two",
        &[],
        "(bw r (* (bw p a) 2))",
        "(bw r (<< (bw p a) 1))",
    );
    let proof_name = eq.find_equivalence(None, None).to_isabelle(&output_dir, true);
    #[cfg(not(feature = "skip_isabelle"))]
    check_isabelle_proof(proof_name, &output_dir).unwrap();
}

