/*
AUTO-GENERATED FILE — DO NOT EDIT
*/
pub fn rule_to_file(input: &str) -> Option<&'static str> {
    match input {
        "add_0" => Some("arith_lemmas"),
        "add_as_xor_and" => Some("mixed_lemmas"),
        "add_eq_prec" => Some("arith_lemmas"),
        "add_full_prec" => Some("arith_lemmas"),
        "add_remove_prec" => Some("arith_lemmas"),
        "and_allones" => Some("bitwise_lemmas"),
        "and_assoc" => Some("bitwise_lemmas"),
        "and_distrib" => Some("bitwise_lemmas"),
        "and_not_self" => Some("bitwise_lemmas"),
        "and_remove" => Some("bitwise_lemmas"),
        "and_self" => Some("bitwise_lemmas"),
        "and_zero" => Some("bitwise_lemmas"),
        "bw_0" => Some("arith_lemmas"),
        "bw_1" => Some("arith_lemmas"),
        "bw_max_val" => Some("arith_lemmas"),
        "bw_pow_sum" => Some("arith_lemmas"),
        "demorg_and" => Some("bitwise_lemmas"),
        "demorg_or" => Some("bitwise_lemmas"),
        "diff_left_eq_prec" => Some("arith_lemmas"),
        "diff_left_remove_prec" => Some("arith_lemmas"),
        "diff_right_eq_prec" => Some("arith_lemmas"),
        "diff_right_remove_prec" => Some("arith_lemmas"),
        "diff_self" => Some("arith_lemmas"),
        "div_div_simp" => Some("arith_lemmas"),
        "div_gte" => Some("arith_lemmas"),
        "div_mult_self" => Some("arith_lemmas"),
        "div_pow_join" => Some("arith_lemmas"),
        "div_same" => Some("arith_lemmas"),
        "int_distrib" => Some("arith_lemmas"),
        "mod_eq" => Some("arith_lemmas"),
        "mul_by_bit" => Some("arith_lemmas"),
        "mul_by_bit_eq" => Some("arith_lemmas"),
        "mul_eq_prec" => Some("arith_lemmas"),
        "mul_full_prec" => Some("arith_lemmas"),
        "mul_pow2" => Some("arith_lemmas"),
        "mul_remove_prec" => Some("arith_lemmas"),
        "mult_0" => Some("arith_lemmas"),
        "mult_1" => Some("arith_lemmas"),
        "mult_2" => Some("arith_lemmas"),
        "neg_not" => Some("mixed_lemmas"),
        "not_0_allones" => Some("bitwise_lemmas"),
        "not_bw_not" => Some("bitwise_lemmas"),
        "not_not" => Some("bitwise_lemmas"),
        "or_allones" => Some("bitwise_lemmas"),
        "or_assoc" => Some("bitwise_lemmas"),
        "or_not_self" => Some("bitwise_lemmas"),
        "or_remove" => Some("bitwise_lemmas"),
        "or_self" => Some("bitwise_lemmas"),
        "or_zero" => Some("bitwise_lemmas"),
        "reduce_mod" => Some("arith_lemmas"),
        "reduce_mod_bis" => Some("arith_lemmas"),
        "sub_to_neg" => Some("arith_lemmas"),
        "unused_generic_or_simpl" => Some("bitwise_lemmas"),
        "xor_allones" => Some("bitwise_lemmas"),
        "xor_and_or" => Some("bitwise_lemmas"),
        "xor_and_or_help" => Some("bitwise_lemmas"),
        "xor_as_or_and" => Some("mixed_lemmas"),
        "xor_remove" => Some("bitwise_lemmas"),
        _ => None,
    }
}
