on:
    pull_request:
        branches: ['main']
    push:
        branches: ['main']

name: CI / Cargo Build & Parallel Tests

jobs:
  test-validate:
    name: Benchmark validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run validation
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release validate

  test-equiv:
    name: Test equivalence
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run equivalence finding
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release find_equiv
